package com.example.project.Airport;
import java.util.ArrayList;

public class Airport  {
    /** A list of the flights into and out of this airport
     *  Guaranteed not to be null and to contain only non-null entries
     */
    private ArrayList<Flight> allFlights;

    public Airport(ArrayList<Flight> flights) {
        allFlights = flights;
    }

    public ArrayList<Flight> getAllFlights() {
        return allFlights;
    }

    /** Returns the revenue generated by all flights at the airport,
     *  as described in part (a)
     */
    public double getTotalRevenue() {
        double c = 0.0;
        for (Flight f : allFlights) {
            if (f.getCapacity() > f.getNumPassengers()) {
                c += f.getPrice() * f.getNumPassengers();
            } else {
                c += f.getPrice() * f.getCapacity();
            }
        }
        return c;
    }

    /** Updates the list of flights by removing certain flights and
     *  returns the total number of passengers whose flights were removed,
     *  as described in part (b)
     */
    public int updateFlights() {
        int c = 0;
        for (int f = 0; f < allFlights.size(); f++) {
            if (!(allFlights.get(f).getNumPassengers() > allFlights.get(f).getCapacity() * 0.2)) {
                c += allFlights.get(f).getNumPassengers();
                allFlights.remove(f);
                f--;
            }
        }
        return c;
    }
}